### ISSUE TITLE
March 32

### ISSUE THREAD

**Issue by johandweber** [koepferl/COVID19Dahoam#1]
Hallo,

thanks a lot for your work.

I noticed that there is the caption "Fit am 32. März" instead of "Fit am 1. April".

Cheers and stay healthy,

Johann

**Comment by johandweber** [comment]
O.K.,

i see that this is intentional to have an monotonically rising number of days.

**Comment by koepferl** [comment]
Hi Johann, 
yes I so that, but I removed it by now. See the newest release.
